export const VIEW_PROPS = [
 'children',
 'hitSlop',
 'id',
 'needsOffscreenAlphaCompositing',
 'onLayout',
 'pointerEvents',
 'removeClippedSubviews',
 'style',
 'testID',
 'nativeID',
];

export const VIEW_PROPS_ANDROID = [
 'collapsable',
 'renderToHardwareTextureAndroid',
 'focusable',
 'tabIndex',
];

export const VIEW_PROPS_IOS = [
 'shouldRasterizeIOS',
 'isTVSelectable',
 'hasTVPreferredFocus',
 'tvParallaxProperties',
 'tvParallaxShiftDistanceX',
 'tvParallaxShiftDistanceY',
 'tvParallaxTiltAngle',
 'tvParallaxMagnification',
];

export const GESTURE_PROPS = [
 'onStartShouldSetResponder',
 'onMoveShouldSetResponder',
 'onResponderEnd',
 'onResponderGrant',
 'onResponderReject',
 'onResponderMove',
 'onResponderRelease',
 'onResponderStart',
 'onResponderTerminationRequest',
 'onResponderTerminate',
 'onStartShouldSetResponderCapture',
 'onMoveShouldSetResponderCapture',
];

export const TOUCHABLE_PROPS = [
 'onTouchStart',
 'onTouchMove',
 'onTouchEnd',
 'onTouchCancel',
 'onTouchEndCapture',
 'TOUCH_TARGET_DEBUG',
 'renderDebugView',
];

export const POINTER_EVENT_PROPS = [
 'onPointerEnter',
 'onPointerLeave',
 'onPointerLeaveCapture',
 'onPointerMove',
 'onPointerMoveCapture',
 'onPointerCancel',
 'onPointerCancelCapture',
 'onPointerDown',
 'onPointerDownCapture',
 'onPointerUp',
 'onPointerUpCapture',
 'onPointerEnterCapture'
];

export const VIEW_STYLE_PROPS = [
 'backfaceVisibility',
 'backgroundColor',
 'borderBlockColor',
 'borderBlockEndColor',
 'borderBlockStartColor',
 'borderBottomColor',
 'borderBottomEndRadius',
 'borderBottomLeftRadius',
 'borderBottomRightRadius',
 'borderBottomStartRadius',
 'borderColor',
 'borderCurve',
 'borderEndColor',
 'borderEndEndRadius',
 'borderEndStartRadius',
 'borderLeftColor',
 'borderRadius',
 'borderRightColor',
 'borderStartColor',
 'borderStartEndRadius',
 'borderStartStartRadius',
 'borderStyle',
 'borderTopColor',
 'borderTopEndRadius',
 'borderTopLeftRadius',
 'borderTopRightRadius',
 'borderTopStartRadius',
 'opacity',
 'elevation',
 'pointerEvents',
 'cursor',
];

export const VIEW_STYLE_FLEX_PROPS = [
 'alignContent',
 'alignItems',
 'alignSelf',
 'aspectRatio',
 'borderBottomWidth',
 'borderEndWidth',
 'borderLeftWidth',
 'borderRightWidth',
 'borderStartWidth',
 'borderTopWidth',
 'borderWidth',
 'bottom',
 'display',
 'end',
 'flex',
 'flexBasis',
 'flexDirection',
 'rowGap',
 'gap',
 'columnGap',
 'flexGrow',
 'flexShrink',
 'flexWrap',
 'height',
 'justifyContent',
 'left',
 'margin',
 'marginBottom',
 'marginEnd',
 'marginHorizontal',
 'marginLeft',
 'marginRight',
 'marginStart',
 'marginTop',
 'marginVertical',
 'maxHeight',
 'maxWidth',
 'minHeight',
 'minWidth',
 'overflow',
 'padding',
 'paddingBottom',
 'paddingEnd',
 'paddingHorizontal',
 'paddingLeft',
 'paddingRight',
 'paddingStart',
 'paddingTop',
 'paddingVertical',
 'position',
 'right',
 'start',
 'top',
 'width',
 'zIndex',
 'direction',
];

export const VIEW_STYLE_SHADOW_PROPS = [
 'shadowColor',
 'shadowOffset',
 'shadowOpacity',
 'shadowRadius',
];

export const TRANSFORM_STYLE_PROPS = [
 'transform',
 'transformOrigin',
 'transformMatrix',
 'rotation',
 'scaleX',
 'scaleY',
 'translateX',
 'translateY',
];